name: oscilloscope
version: 0.1.0
author: bob_twinkles
main: tk.sirtwinkles.oscilloscope.OSPlugin
commands:
  setType:
    description: Sets an oscilloscope type
    usage: /setType <ScopeID> <logic|analog>
  oscilloscopeMenu:
    desciption: Displays a menu of oscilloscope actions
    usage: /oscilloscopeMenu <ScopeID>